FROM node:12
# Create app directory
WORKDIR /upendencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY app.js /

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
#COPY . .


CMD [ "node", "app.js" ]
